--	*********************
--	 게시판  관련 SQL 작성
--	********************
--	users 테이블 생성 구문 
--	     id          
--	     password   
--	     name        
--	     role       -- admin / user
--	
--	board 테이블 생성 구문 
--	     seq		-- num of content	
--	     title      
--	     content
--	     regdate	-- date
--	     cnt		-- view count 
--	     id      
--	     
--	
--	회원등록
--	회원정보수정
--	로그인
--	
--	게시판 글등록
--	글수정
--	게시판 글 삭제
--	
--	데이터검색(Query)
--	전체 등록글 수
--	사용자별 등록글수 
--	월별개시글수
--	사용자별 게시글 검색
--	제목으로 게시글 검색

-- SCOTT/TIGER
