conn hr/hr

--문제1
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_NAME,M.FIRST_NAME
FROM EMPLOYEES E, EMPLOYEES M,DEPARTMENTS D
WHERE E.MANAGER_ID = M.EMPLOYEE_ID AND E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--문제2
SELECT E.LAST_NAME, E.SALARY
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID = M.EMPLOYEE_ID AND E.SALARY > M.SALARY;   

--문제3
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID AND E.SALARY BETWEEN 9000 AND 10000 AND J.JOB_TITLE = 'SALES REPRESENTATIVE';

--문제4
SELECT E.EMPLOYEE_ID,E.LAST_NAME, TO_CHAR(E.HIRE_DATE,'YYYY-MM-DD') AS HIREDATE
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID = M.EMPLOYEE_ID AND E.HIRE_DATE < M.HIRE_DATE;

--문제5
SELECT E.FIRST_NAME, TO_CHAR(E.HIRE_DATE, 'YYYY-MM-DD AM HH12:MI:SS') AS HIRE_DATE, E.MANAGER_ID, M.FIRST_NAME
FROM EMPLOYEES E LEFT JOIN EMPLOYEES M 
ON E.MANAGER_ID = M.EMPLOYEE_ID 
WHERE TO_CHAR(E.HIRE_DATE, 'YYYY') = 2008;

--문제6
SELECT E.FIRST_NAME, E.SALARY, D.DEPARTMENT_NAME 
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.DEPARTMENT_NAME = 'SALES';

--문제7
SELECT TO_CHAR(E.HIRE_DATE,'MM') AS MONTH,COUNT(*)
FROM EMPLOYEES E
GROUP BY TO_CHAR(E.HIRE_DATE,'MM')
ORDER BY MONTH;

